#!/usr/bin/env node
/**
 * Generates the Windows application icon (`build-resources/icon.ico`) from code (spec 0022, T-0022-12).
 *
 * Why a generator and not just a committed binary: the installer must be REPRODUCIBLE. A
 * hand-made .ico is an opaque blob nobody can re-derive, diff, or re-render at another size; if it
 * is ever lost or corrupted the installer silently falls back to the default Electron icon. The
 * artwork here is pure deterministic math (no fonts, no randomness, no network, no dependencies),
 * so `node scripts/generate-icon.mjs` produces byte-identical output on any machine and
 * `src/desktop/icon.test.ts` proves the committed .ico is exactly what this script emits.
 *
 * Artwork: an isometric block on the app's own dark background (#0f1117, the BrowserWindow
 * backgroundColor) — a Minecraft block reads at 16x16, which a logotype would not.
 *
 * Format: a classic ICO directory. Entries <= 128px are 32-bit BGRA BMPs (the universally
 * understood form); the 256px entry is a PNG payload, which is how Windows has carried 256px
 * icons since Vista and what electron-builder expects to find.
 *
 * Usage: node scripts/generate-icon.mjs [--check]
 *   (no flag)  write build-resources/icon.ico
 *   --check    exit 1 if the committed file differs from freshly generated bytes
 */
import { deflateSync } from 'node:zlib';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(repoRoot, 'build-resources/icon.ico');

/** Icon sizes Windows actually asks for: tray/menu, list views, desktop, and the Vista+ 256 tile. */
const SIZES = [16, 24, 32, 48, 64, 128, 256];

const COLORS = {
  background: [0x0f, 0x11, 0x17],
  panel: [0x17, 0x1b, 0x26],
  top: [0x5e, 0xd6, 0x9a],
  left: [0x6b, 0x4c, 0x32],
  right: [0x8f, 0x67, 0x40],
  edge: [0x0b, 0x0d, 0x12],
};

/**
 * Renders the icon at `size` into a straight (non-premultiplied) RGBA buffer.
 *
 * Coordinates are normalised to the unit square so every size is the same drawing, and each pixel
 * is sampled on a 4x4 grid so edges are antialiased without any image library.
 */
function render(size) {
  const rgba = Buffer.alloc(size * size * 4);
  const SS = 4; // supersampling grid per axis
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let sy = 0; sy < SS; sy += 1) {
        for (let sx = 0; sx < SS; sx += 1) {
          const u = (x + (sx + 0.5) / SS) / size;
          const v = (y + (sy + 0.5) / SS) / size;
          const [pr, pg, pb, pa] = sample(u, v);
          r += pr;
          g += pg;
          b += pb;
          a += pa;
        }
      }
      const n = SS * SS;
      const o = (y * size + x) * 4;
      rgba[o] = Math.round(r / n);
      rgba[o + 1] = Math.round(g / n);
      rgba[o + 2] = Math.round(b / n);
      rgba[o + 3] = Math.round(a / n);
    }
  }
  return rgba;
}

/** Colour of the artwork at unit coordinates (u, v), both in [0, 1). Returns [r, g, b, a]. */
function sample(u, v) {
  // Rounded-square plate, inset slightly so the icon breathes in a taskbar.
  const inset = 0.03;
  const radius = 0.2;
  if (!insideRoundedRect(u, v, inset, 1 - inset, radius)) return [0, 0, 0, 0];

  // Subtle vertical lift so the plate is not a dead flat fill at large sizes.
  const lift = v * 0.35;
  const plate = mix(COLORS.background, COLORS.panel, lift);

  // Isometric block: a 2:1 diamond top with two side faces below it.
  const cx = 0.5;
  const cy = 0.45;
  const w = 0.28; // half width of the diamond
  const q = w / 2; // half height of the diamond (2:1 isometric)
  const body = 0.26; // vertical height of the side faces

  const top = [
    [cx - w, cy],
    [cx, cy - q],
    [cx + w, cy],
    [cx, cy + q],
  ];
  const left = [
    [cx - w, cy],
    [cx, cy + q],
    [cx, cy + q + body],
    [cx - w, cy + body],
  ];
  const right = [
    [cx + w, cy],
    [cx, cy + q],
    [cx, cy + q + body],
    [cx + w, cy + body],
  ];

  if (inPolygon(u, v, top)) return [...shade(COLORS.top, (u - cx) / w * 0.06), 255];
  if (inPolygon(u, v, left)) return [...shade(COLORS.left, (v - cy) * 0.1), 255];
  if (inPolygon(u, v, right)) return [...shade(COLORS.right, (v - cy) * 0.1), 255];

  return [...plate, 255];
}

function shade(color, amount) {
  const target = amount >= 0 ? [255, 255, 255] : [0, 0, 0];
  return mix(color, target, Math.min(Math.abs(amount), 1));
}

function mix(a, b, t) {
  return [
    Math.round(a[0] + (b[0] - a[0]) * t),
    Math.round(a[1] + (b[1] - a[1]) * t),
    Math.round(a[2] + (b[2] - a[2]) * t),
  ];
}

function insideRoundedRect(u, v, min, max, radius) {
  if (u < min || u > max || v < min || v > max) return false;
  const r = Math.min(radius, (max - min) / 2);
  const corners = [
    [min + r, min + r, u < min + r && v < min + r],
    [max - r, min + r, u > max - r && v < min + r],
    [min + r, max - r, u < min + r && v > max - r],
    [max - r, max - r, u > max - r && v > max - r],
  ];
  for (const [ccx, ccy, active] of corners) {
    if (active && Math.hypot(u - ccx, v - ccy) > r) return false;
  }
  return true;
}

/** Standard ray-casting point-in-polygon; the polygons here are convex quads. */
function inPolygon(u, v, points) {
  let inside = false;
  for (let i = 0, j = points.length - 1; i < points.length; j = i, i += 1) {
    const [xi, yi] = points[i];
    const [xj, yj] = points[j];
    if (yi > v !== yj > v && u < ((xj - xi) * (v - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

/** ICO BMP entry: BITMAPINFOHEADER with doubled height, bottom-up BGRA rows, then the AND mask. */
function bmpEntry(size, rgba) {
  const header = Buffer.alloc(40);
  header.writeUInt32LE(40, 0); // biSize
  header.writeInt32LE(size, 4); // biWidth
  header.writeInt32LE(size * 2, 8); // biHeight — colour rows + mask rows
  header.writeUInt16LE(1, 12); // biPlanes
  header.writeUInt16LE(32, 14); // biBitCount
  header.writeUInt32LE(0, 16); // BI_RGB

  const pixels = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y += 1) {
    const src = (size - 1 - y) * size * 4; // bottom-up
    for (let x = 0; x < size; x += 1) {
      const s = src + x * 4;
      const d = (y * size + x) * 4;
      pixels[d] = rgba[s + 2]; // B
      pixels[d + 1] = rgba[s + 1]; // G
      pixels[d + 2] = rgba[s]; // R
      pixels[d + 3] = rgba[s + 3]; // A
    }
  }

  // 1bpp AND mask, rows padded to 4 bytes. Zero = "use the alpha channel", correct for 32-bit icons.
  const maskStride = Math.ceil(size / 32) * 4;
  const mask = Buffer.alloc(maskStride * size);

  return Buffer.concat([header, pixels, mask]);
}

/** Minimal PNG encoder (8-bit RGBA, no interlacing) — deterministic, stdlib only. */
function pngEntry(size, rgba) {
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y += 1) {
    raw[y * (size * 4 + 1)] = 0; // filter type 0 (None): keeps the output byte-stable
    rgba.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4);
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // adaptive filtering
  ihdr[12] = 0; // no interlace

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([length, body, crc]);
}

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

/** Assembles the ICO container: 6-byte header, one 16-byte directory entry per size, then payloads. */
export function buildIco() {
  const images = SIZES.map((size) => {
    const rgba = render(size);
    return { size, data: size === 256 ? pngEntry(size, rgba) : bmpEntry(size, rgba) };
  });

  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type 1 = icon
  header.writeUInt16LE(images.length, 4);

  const directory = Buffer.alloc(16 * images.length);
  let offset = header.length + directory.length;
  images.forEach((image, index) => {
    const at = index * 16;
    directory[at] = image.size === 256 ? 0 : image.size; // 0 means 256 in the ICO directory
    directory[at + 1] = image.size === 256 ? 0 : image.size;
    directory[at + 2] = 0; // palette colours
    directory[at + 3] = 0; // reserved
    directory.writeUInt16LE(1, at + 4); // colour planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(image.data.length, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += image.data.length;
  });

  return Buffer.concat([header, directory, ...images.map((image) => image.data)]);
}

async function main() {
  const ico = buildIco();
  if (process.argv.includes('--check')) {
    const committed = await readFile(OUTPUT).catch(() => null);
    if (committed === null) {
      console.error(`missing ${OUTPUT} — run: node scripts/generate-icon.mjs`);
      process.exit(1);
    }
    if (!committed.equals(ico)) {
      console.error(`${OUTPUT} differs from generated output — run: node scripts/generate-icon.mjs`);
      process.exit(1);
    }
    console.log(`build-resources/icon.ico matches the generator (${ico.length} bytes, sizes ${SIZES.join('/')})`);
    return;
  }
  await mkdir(dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, ico);
  console.log(`wrote build-resources/icon.ico (${ico.length} bytes, sizes ${SIZES.join('/')})`);
}

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('generate-icon.mjs')) {
  await main();
}
